[openai]
api_key = "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"

[database]
url = "postgresql+psycopg2://avnadmin:AVNS_R6RE-o-OUS9CapOrd1u@pg-338e7d49-sjinnovation.f.aivencloud.com:21557/defaultdb?sslmode=require"